#!/usr/bin/env python3
"""generate_report.py — Generate a summary HTML report for pipeline results.

Produces a self-contained HTML page showing:
  1. Junction origin summary — counts of tumor_specific vs patient_specific
     junctions per sample, so results can be quickly verified.
  2. Top strong binders — the highest-affinity predicted neoepitopes
     (IC50 < strong threshold).

Usage (standalone):
  python generate_report.py \\
      --novel-junctions results/junctions/local/novel_junctions.tsv \\
      --predictions results/predictions/local/predictions.tsv \\
      --output results/reports/local/report.html

Usage (Snakemake):
  Called automatically by the ``generate_report`` rule.
"""

import argparse
import logging
from pathlib import Path

import pandas as pd

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HTML helpers
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Splice Neoepitope Report</title>
  <style>
    body  {{ font-family: Arial, sans-serif; margin: 2em; color: #333; }}
    h1    {{ color: #2c3e50; }}
    h2    {{ color: #34495e; border-bottom: 1px solid #ccc; padding-bottom: 4px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
    th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; }}
    th    {{ background-color: #f2f2f2; }}
    tr:nth-child(even) {{ background-color: #f9f9f9; }}
    .label-ts  {{ color: #27ae60; font-weight: bold; }}
    .label-ps  {{ color: #e67e22; }}
  </style>
</head>
<body>
  <h1>Splice Neoepitope Pipeline Report</h1>
  <p>Generated by the splice neoepitope pipeline
     (reimplementation of Lee et al., 2015).</p>

  <h2>Junction origin summary</h2>
  <p>Unannotated junctions classified by comparison against the matched
  normal sample. Only <span class="label-ts">tumor_specific</span>
  junctions enter neoepitope prediction.</p>
  {origin_table}

  <h2>Neoepitope prediction summary</h2>
  {binder_table}

  <h2>Top strong binders (IC50 &lt; {ic50_strong} nM)</h2>
  {strong_table}

  <hr/>
  <p><small>Pipeline source:
  <a href="https://github.com/Jin-HoMLee/splice-neoepitope-pipeline">
  splice-neoepitope-pipeline</a>.
  Original work: Jin-Ho Lee, Seoul National University, 2015.</small></p>
</body>
</html>
"""


def _df_to_html(df: pd.DataFrame, max_rows: int = 100) -> str:
    if df.empty:
        return "<p><em>No data.</em></p>"
    out = df.head(max_rows).to_html(index=False, border=0, escape=True)
    if len(df) > max_rows:
        out += f"<p><em>Showing {max_rows} of {len(df)} rows.</em></p>"
    return out


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_report(
    novel_junctions_tsv: str | Path,
    predictions_tsv: str | Path,
    output_html: str | Path,
    ic50_strong: float = 50.0,
) -> None:
    """Generate the summary HTML report.

    Args:
        novel_junctions_tsv: Classified junctions TSV (with junction_origin column).
        predictions_tsv:     MHCflurry predictions TSV.
        output_html:         Destination HTML file.
        ic50_strong:         Strong-binder IC50 threshold (nM).
    """
    output_html = Path(output_html)
    output_html.parent.mkdir(parents=True, exist_ok=True)

    junc_df = pd.read_csv(novel_junctions_tsv, sep="\t")
    pred_df = pd.read_csv(predictions_tsv, sep="\t")

    # --- Junction origin summary ---
    if junc_df.empty or "junction_origin" not in junc_df.columns:
        origin_df = pd.DataFrame(
            columns=["sample_id", "sample_type", "unannotated", "patient_specific", "tumor_specific"]
        )
    else:
        origin_rows = []
        for sample_id, grp in junc_df.groupby("sample_id"):
            sample_type = grp["sample_type"].iloc[0]
            counts = grp["junction_origin"].value_counts()
            origin_rows.append({
                "sample_id": sample_id,
                "sample_type": sample_type,
                "unannotated": len(grp),
                "patient_specific": counts.get("patient_specific", 0),
                "tumor_specific": counts.get("tumor_specific", 0),
            })
        origin_df = pd.DataFrame(origin_rows)

    origin_html = _df_to_html(origin_df)

    # --- Binder summary ---
    if pred_df.empty:
        binder_html = "<p><em>No predictions available.</em></p>"
    else:
        binder_counts = pred_df["binder_class"].value_counts().reset_index()
        binder_counts.columns = ["binder_class", "count"]
        binder_html = _df_to_html(binder_counts)

    # --- Top strong binders ---
    if pred_df.empty:
        strong_html = "<p><em>No predictions available.</em></p>"
    else:
        strong_df = pred_df[pred_df["binder_class"] == "strong"].sort_values("ic50_nM")
        strong_cols = [c for c in ["source_header", "peptide_9mer", "allele", "ic50_nM", "rank"]
                       if c in strong_df.columns]
        strong_html = _df_to_html(strong_df[strong_cols], max_rows=50)

    html = _HTML_TEMPLATE.format(
        origin_table=origin_html,
        binder_table=binder_html,
        strong_table=strong_html,
        ic50_strong=int(ic50_strong),
    )
    output_html.write_text(html, encoding="utf-8")
    log.info("Report written to %s", output_html)


# ---------------------------------------------------------------------------
# Snakemake / CLI entry point
# ---------------------------------------------------------------------------

def _snakemake_main() -> None:
    log_file = snakemake.log[0]  # type: ignore[name-defined]  # noqa: F821
    logging.getLogger().addHandler(logging.FileHandler(log_file))

    generate_report(
        novel_junctions_tsv=snakemake.input.novel_junctions,  # type: ignore[name-defined]  # noqa: F821
        predictions_tsv=snakemake.input.predictions_tsv,  # type: ignore[name-defined]  # noqa: F821
        output_html=snakemake.output.report_html,  # type: ignore[name-defined]  # noqa: F821
        ic50_strong=float(snakemake.params.ic50_strong),  # type: ignore[name-defined]  # noqa: F821
    )


def _cli_main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate summary HTML report from pipeline results."
    )
    parser.add_argument("--novel-junctions", required=True, help="Classified junctions TSV")
    parser.add_argument("--predictions", required=True, help="MHCflurry predictions TSV")
    parser.add_argument("--output", required=True, help="Output HTML report")
    parser.add_argument("--ic50-strong", type=float, default=50.0)
    args = parser.parse_args()

    generate_report(
        novel_junctions_tsv=args.novel_junctions,
        predictions_tsv=args.predictions,
        output_html=args.output,
        ic50_strong=args.ic50_strong,
    )


if __name__ == "__main__":
    try:
        snakemake  # type: ignore[name-defined]  # noqa: F821
        _snakemake_main()
    except NameError:
        _cli_main()
