#!/usr/bin/env python3
"""generate_report.py — Generate a summary HTML report for pipeline results.

Produces a self-contained HTML page showing:
  1. Junction origin summary — counts of tumor_specific vs patient_specific
     junctions per sample, so results can be quickly verified.
  2. Top strong binders — the highest-affinity predicted neoepitopes
     (IC50 < strong threshold).

Usage (standalone):
  python generate_report.py \\
      --novel-junctions results/junctions/local/novel_junctions.tsv \\
      --predictions results/predictions/local/predictions.tsv \\
      --output results/reports/local/report.html

Usage (Snakemake):
  Called automatically by the ``generate_report`` rule.
"""

import argparse
import html
import logging
from pathlib import Path

import pandas as pd
from Bio import SeqIO

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HTML helpers
# ---------------------------------------------------------------------------

_PIPELINE_DIAGRAM = """\
<div class="pipeline">
  <div class="step io">RNA-Seq reads<br/><small>tumor + normal</small></div>
  <div class="arrow">↓</div>
  <div class="step">HISAT2 alignment<br/><small>junction extraction with regtools</small></div>
  <div class="arrow">↓</div>
  <div class="step filter">GENCODE reference filter<br/><small>remove annotated junctions</small></div>
  <div class="arrow">↓ unannotated junctions</div>
  <div class="step split-wrap">
    <div class="split-header">Normal sample comparison</div>
    <div class="split-row">
      <div class="split-left">
        <strong>patient_specific</strong><br/>
        <small>also in normal tissue</small><br/>
        <span class="discard">→ excluded</span>
      </div>
      <div class="split-right">
        <strong>tumor_specific</strong><br/>
        <small>absent in normal tissue</small><br/>
        <span class="keep">→ keep ↓</span>
      </div>
    </div>
  </div>
  <div class="arrow">↓</div>
  <div class="step">Contig assembly<br/><small>50 nt per junction</small></div>
  <div class="arrow">↓</div>
  <div class="step">In-silico translation<br/><small>3 reading frames → junction-spanning 9-mers</small></div>
  <div class="arrow">↓</div>
  <div class="step">MHCflurry epitope prediction<br/><small>IC50 affinity per 9-mer</small></div>
  <div class="arrow">↓</div>
  <div class="step io">Neoepitope candidates<br/><small>strong / weak binders</small></div>
</div>
"""

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Splice Neoepitope Report</title>
  <style>
    body  {{ font-family: Arial, sans-serif; margin: 2em; color: #333; }}
    h1    {{ color: #2c3e50; }}
    h2    {{ color: #34495e; border-bottom: 1px solid #ccc; padding-bottom: 4px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
    th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; }}
    th    {{ background-color: #f2f2f2; }}
    tr:nth-child(even) {{ background-color: #f9f9f9; }}

    /* Pipeline diagram */
    .pipeline {{
      display: flex; flex-direction: column; align-items: center;
      max-width: 420px; margin: 1.5em auto;
    }}
    .step {{
      background: #eaf4fb; border: 1px solid #3498db; border-radius: 6px;
      padding: 10px 18px; text-align: center; width: 100%;
      box-sizing: border-box; font-size: 0.95em;
    }}
    .step.io     {{ background: #eafaf1; border-color: #27ae60; }}
    .step.filter {{ background: #fef9e7; border-color: #f39c12; }}
    .arrow {{ color: #888; font-size: 1.3em; margin: 3px 0; line-height: 1; }}
    .split-wrap {{
      width: 100%; border: 1px solid #3498db; border-radius: 6px;
      overflow: hidden; font-size: 0.95em;
    }}
    .split-header {{
      background: #eaf4fb; padding: 8px 12px; text-align: center;
      border-bottom: 1px solid #3498db;
    }}
    .split-row   {{ display: flex; }}
    .split-left  {{
      flex: 1; background: #fdecea; padding: 10px 12px; text-align: center;
      border-right: 1px solid #ddd;
    }}
    .split-right {{ flex: 1; background: #eafaf1; padding: 10px 12px; text-align: center; }}
    .discard {{ color: #c0392b; }}
    .keep    {{ color: #27ae60; }}

    /* Contig visualisation */
    .contig  {{ font-family: monospace; font-size: 0.85em; white-space: nowrap; }}
    .nt-up   {{ color: #555; }}
    .nt-down {{ color: #555; }}
    .nt-pep-up   {{ background: #d6eaf8; color: #1a5276; font-weight: bold; }}
    .nt-pep-down {{ background: #d5f5e3; color: #1e8449; font-weight: bold; }}
    .junction-mark {{ color: #e74c3c; font-weight: bold; }}
  </style>
</head>
<body>
  <h1>Splice Neoepitope Pipeline Report</h1>
  <p>Generated by the splice neoepitope pipeline
     (reimplementation of Lee et al., 2015).</p>

  <h2>Pipeline overview</h2>
  {pipeline_diagram}

  <h2>Junction origin summary</h2>
  <p>Splice junctions detected in the tumor that are absent from the GENCODE
  reference annotation, grouped by whether they also appear in the matched normal
  tissue. Only <strong class="keep">tumor_specific</strong> junctions — absent
  from both the reference and the normal sample — are used for neoepitope
  prediction. <strong class="discard">patient_specific</strong> junctions are
  present in normal tissue and are therefore not tumor-derived.</p>
  {origin_table}

  <h2>Neoepitope prediction summary</h2>
  {binder_table}

  <h2>Top strong binders (IC50 &lt; {ic50_strong} nM)</h2>
  {strong_table}

  <hr/>
  <p><small>Pipeline source:
  <a href="https://github.com/Jin-HoMLee/splice-neoepitope-pipeline">
  splice-neoepitope-pipeline</a>.
  Original work: Jin-Ho Lee, Seoul National University, 2015.</small></p>
</body>
</html>
"""


def _load_contigs(contigs_fasta: str | Path) -> dict[str, str]:
    """Parse contigs FASTA into {contig_key: sequence} dict.

    The contig key matches the contig_key column in the predictions TSV.
    """
    contigs: dict[str, str] = {}
    for record in SeqIO.parse(contigs_fasta, "fasta"):
        contigs[record.description] = str(record.seq).upper()
    return contigs


def _render_contig(seq: str, start_nt: int, end_nt_incl: int,
                   upstream_nt: int = 26) -> str:
    """Render a 50 nt contig as HTML with junction marker and peptide highlighted."""
    html_parts = []
    for i, nt in enumerate(seq):
        if i == upstream_nt:
            html_parts.append('<span class="junction-mark">|</span>')
        in_pep = start_nt <= i <= end_nt_incl
        if in_pep and i < upstream_nt:
            html_parts.append(f'<span class="nt-pep-up">{nt}</span>')
        elif in_pep:
            html_parts.append(f'<span class="nt-pep-down">{nt}</span>')
        elif i < upstream_nt:
            html_parts.append(f'<span class="nt-up">{nt}</span>')
        else:
            html_parts.append(f'<span class="nt-down">{nt}</span>')
    return f'<span class="contig">{"".join(html_parts)}</span>'


def _build_strong_table_html(
    pred_df: pd.DataFrame,
    contigs: dict[str, str],
    upstream_nt: int = 26,
    max_rows: int = 50,
) -> str:
    """Build the top strong binders table with a contig visualisation column."""
    strong_df = pred_df[pred_df["binder_class"] == "strong"].sort_values("ic50_nM")
    if strong_df.empty:
        return "<p><em>No strong binders found.</em></p>"

    rows = []
    for _, row in strong_df.head(max_rows).iterrows():
        contig_key = row["contig_key"]
        start_nt = int(row["start_nt"])
        end_nt_incl = start_nt + 26  # 9 aa × 3 nt − 1

        seq = contigs.get(contig_key, "")
        contig_html = _render_contig(seq, start_nt, end_nt_incl, upstream_nt) if seq else "<em>n/a</em>"

        rows.append(
            f"<tr>"
            f"<td>{html.escape(str(row['contig_key']))}</td>"
            f"<td>{html.escape(str(row['peptide']))}</td>"
            f"<td>{html.escape(str(row['allele']))}</td>"
            f"<td>{row['ic50_nM']:.1f}</td>"
            f"<td>{row['percentile_rank']:.3f}</td>"
            f"<td>{contig_html}</td>"
            f"</tr>"
        )

    legend = (
        "upstream <span class='junction-mark'>|</span> downstream — "
        "<span class='nt-pep-up'>peptide (upstream)</span> "
        "<span class='nt-pep-down'>peptide (downstream)</span>"
    )
    percentile_header = (
        "<th title='Percentage of random peptides that bind worse than this one. "
        "Lower is better — &lt;2% is the standard binder threshold.'>Percentile rank ▾</th>"
    )
    table = (
        f"<table><thead><tr>"
        f"<th>Source</th><th>9-mer</th><th>Allele</th><th>IC50 (nM)</th>"
        f"{percentile_header}"
        f"<th>Contig ({legend})</th>"
        f"</tr></thead><tbody>{''.join(rows)}</tbody></table>"
    )
    if len(strong_df) > max_rows:
        table += f"<p><em>Showing {max_rows} of {len(strong_df)} rows.</em></p>"
    return table


def _df_to_html(df: pd.DataFrame, max_rows: int = 100) -> str:
    if df.empty:
        return "<p><em>No data.</em></p>"
    out = df.head(max_rows).to_html(index=False, border=0, escape=True)
    if len(df) > max_rows:
        out += f"<p><em>Showing {max_rows} of {len(df)} rows.</em></p>"
    return out


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_report(
    novel_junctions_tsv: str | Path,
    predictions_tsv: str | Path,
    output_html: str | Path,
    contigs_fasta: str | Path | None = None,
    ic50_strong: float = 50.0,
) -> None:
    """Generate the summary HTML report.

    Args:
        novel_junctions_tsv: Classified junctions TSV (with junction_origin column).
        predictions_tsv:     MHCflurry predictions TSV.
        output_html:         Destination HTML file.
        contigs_fasta:       Contig FASTA for junction visualisation (optional).
        ic50_strong:         Strong-binder IC50 threshold (nM).
    """
    output_html = Path(output_html)
    output_html.parent.mkdir(parents=True, exist_ok=True)

    junc_df = pd.read_csv(novel_junctions_tsv, sep="\t")
    pred_df = pd.read_csv(predictions_tsv, sep="\t")
    contigs = _load_contigs(contigs_fasta) if contigs_fasta else {}

    # --- Junction origin summary ---
    if junc_df.empty or "junction_origin" not in junc_df.columns:
        origin_df = pd.DataFrame(
            columns=["sample_id", "sample_type", "unannotated", "patient_specific", "tumor_specific"]
        )
    else:
        origin_rows = []
        for sample_id, grp in junc_df.groupby("sample_id"):
            sample_type = grp["sample_type"].iloc[0]
            counts = grp["junction_origin"].value_counts()
            origin_rows.append({
                "sample_id": sample_id,
                "sample_type": sample_type,
                "unannotated": len(grp),
                "patient_specific": counts.get("patient_specific", 0),
                "tumor_specific": counts.get("tumor_specific", 0),
            })
        origin_df = pd.DataFrame(origin_rows)

    origin_html = _df_to_html(origin_df)

    # --- Binder summary ---
    if pred_df.empty:
        binder_html = "<p><em>No predictions available.</em></p>"
    else:
        binder_counts = pred_df["binder_class"].value_counts().reset_index()
        binder_counts.columns = ["binder_class", "count"]
        binder_html = _df_to_html(binder_counts)

    # --- Top strong binders with contig visualisation ---
    if pred_df.empty:
        strong_html = "<p><em>No predictions available.</em></p>"
    else:
        strong_html = _build_strong_table_html(pred_df, contigs)

    html = _HTML_TEMPLATE.format(
        pipeline_diagram=_PIPELINE_DIAGRAM,
        origin_table=origin_html,
        binder_table=binder_html,
        strong_table=strong_html,
        ic50_strong=int(ic50_strong),
    )
    output_html.write_text(html, encoding="utf-8")
    log.info("Report written to %s", output_html)


# ---------------------------------------------------------------------------
# Snakemake / CLI entry point
# ---------------------------------------------------------------------------

def _snakemake_main() -> None:
    log_file = snakemake.log[0]  # type: ignore[name-defined]  # noqa: F821
    logging.getLogger().addHandler(logging.FileHandler(log_file))

    generate_report(
        novel_junctions_tsv=snakemake.input.novel_junctions,  # type: ignore[name-defined]  # noqa: F821
        predictions_tsv=snakemake.input.predictions_tsv,  # type: ignore[name-defined]  # noqa: F821
        output_html=snakemake.output.report_html,  # type: ignore[name-defined]  # noqa: F821
        contigs_fasta=snakemake.input.contigs_fasta,  # type: ignore[name-defined]  # noqa: F821
        ic50_strong=float(snakemake.params.ic50_strong),  # type: ignore[name-defined]  # noqa: F821
    )


def _cli_main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate summary HTML report from pipeline results."
    )
    parser.add_argument("--novel-junctions", required=True, help="Classified junctions TSV")
    parser.add_argument("--predictions", required=True, help="MHCflurry predictions TSV")
    parser.add_argument("--output", required=True, help="Output HTML report")
    parser.add_argument("--contigs-fasta", default=None, help="Contigs FASTA for junction visualisation")
    parser.add_argument("--ic50-strong", type=float, default=50.0)
    args = parser.parse_args()

    generate_report(
        novel_junctions_tsv=args.novel_junctions,
        predictions_tsv=args.predictions,
        output_html=args.output,
        contigs_fasta=args.contigs_fasta,
        ic50_strong=args.ic50_strong,
    )


if __name__ == "__main__":
    try:
        snakemake  # type: ignore[name-defined]  # noqa: F821
        _snakemake_main()
    except NameError:
        _cli_main()
